### ISSUE TITLE
specify why students want to put a userid in the cookie (instead of username, for example)

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/ws-session-management#1]
Maybe explicitly state the fact that cookies shouldn't contain sensitive information.

A user ID only identifies who the person actually is, if you have access to the database where the ID is set. If your database has been compromised, you've got bigger problems than cookie content :sweat_smile: 

Whereas an actual username can more easily be related to a particular human being, so this is more sensitive.

**Comment by ronanyeah** [comment]
A username is not sensitive information.
