### ISSUE TITLE
clarity of instructions - using node module in your terminal

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/ws-session-management#15]
Confusion about
> You will be provided a Node.js module (to be used in your terminal)

Probably need to explain to students what is meant by this.

**Comment by ronanyeah** [comment]
https://github.com/foundersandcoders/ws-session-management/commit/3ea9e49445a5cb724571e5a568afa79d249cc596#diff-04c6e90faac2675aa89e2176d2eec7d8R97
