### ISSUE TITLE
really unclear how exercise 1 relates to JWTs

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/ws-session-management#16]
Unexplained jump between exercise 1's `validate` function & then `jwt.verify`.

Without this explanation, or a more thorough explanation of what JWTs are and how they work #10, students are likely to think that `jwt.verify` is doing the same thing they just implemented in `psst.validate` in exercise 1.

**Comment by ronanyeah** [comment]
Yeah totally agree, the JWT section is rushed.

**Comment by mattlub** [comment]
it is the same though right? JWT uses an HMAC

**Comment by bobbysebolao** [comment]
Yes I believe exercise 1's ```validate``` function is what ```jwt.verify``` does under the hood in exercise 2. I think they are functionally the same.

**Comment by oliverjam** [comment]
I think this can be closed, since the order of the exercises was switched a while ago, and the readme has had lots of clarification since
