### ISSUE TITLE
move JWT explanation to the top

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/ws-session-management#3]
This part makes it sound like a hash = a signature:
> If you remember from Workshop 1, hashing requires a secret (random string), a value (the string you want to protect) and mathematical algorithm to apply to them.
>
> This produces a random non-sensical result (the signature).

But a salt (random string) + value (password) is not referred to as a signature. This only makes sense within the context of JWTs

**Comment by jsms90** [comment]
Without the JWT explanation, it's also not clear why you would need to do this:
> `const cookieValue = JSON.stringify(userInformation);`

**Comment by ronanyeah** [comment]
Signature is widely used term outside JWT for any type of signing. https://www.npmjs.com/package/cookie-signature

**Comment by jsms90** [comment]
But what's the use in concatenating it to the original and a `.`?

Surely this is just going to raise more questions than it answers, since we don't know about all the other contexts in which you would need to sign something?

Can we not just stick to JWTs, since this is the reason we're introducing signing?

**Comment by ronanyeah** [comment]
I see what you mean but JWTs are a massive abstraction. Starting with which will guarantee that JWTs and signing are too tightly coupled in their heads.

I could change it to something different like instead it sends back an object:
```
{
  value: 'hash me',
  hash: 'ojhiuguinincenvijenvo'
}
```
But thats pointless and now you aren't dealing with a self contained string. You might notice bcrypt also has sections. It's standard signing.

**Comment by ronanyeah** [comment]
I could jazz it up by making it a secret message passing exercise or something. :smile:

**Comment by jsms90** [comment]
We teach hashing as one step along the way to securing a password.

We teaching signing so that people can create a JWT and use that to manage a user's session.

In neither scenario would it be necessary or remotely helpful to put the unhashed version next to the hashed version. Even if that's what you do when you sign something in a different context, I don't see how that's useful to show them here?

**Comment by jsms90** [comment]
Hmm.... nonsense. That's exactly what you're doing with a JWT. You're putting the encoded header & encoded payload (unhashed) next to the signature (hashed). :sweat_smile: 

But I still think this makes _way_ more sense to tell them after introducing the concept of JWTs. Just so they understand why they're being asked to do this at all.

**Comment by ronanyeah** [comment]
Yeah I was about to type that...

**Comment by ronanyeah** [comment]
No, they will learn what generic signing is. Then they will learn a useful application of it. The other way round makes no sense. Can you close this please?
