### ISSUE TITLE
Code example shows signing with a regular hash function, not an HMAC

### ISSUE THREAD

**Issue by Roger-Heathcote** [foundersandcoders/ws-session-management#39]
If my understanding is correct to sign the payload we would need to use a keyed hash function (HMAC) but the example doesn't show this. We have a regular hash function with no mention of the key.

const signature = hashFunction(`${encodedHeader}.${encodedPayload}`);

It should be something more like this...

const signature = HMACFunction(`${encodedHeader}.${encodedPayload}`,"our secret key");

Please correct me if I'm wrong!!

**Comment by oliverjam** [comment]
Yeah I think you're right. That "hashFunction" is just a hypothetical example of how the `jsonwebtoken` library might work, but it's important to give the right impression.

Want to just add the string as the second argument in the example?
