### ISSUE TITLE
only 2 very brief exercises

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/ws-session-management#6]
It won't take students 2 hours to complete the `sign` and `validate` functions.
> TODO
>
> + more JWT info (eg headers, claims)
> + a JWT exercise

What exactly is still coming for tomorrow @ronanyeah?

**Comment by ronanyeah** [comment]
Suggestions are welcome. I'd literally have to make up useless work.
1. Making your own signing function and
2. Understanding what a JWT is is all there is to it

**Comment by mattlub** [comment]
has this been resolved now with the JWT exercise?
