### ISSUE TITLE
explain what HMAC is

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/ws-session-management#7]
This sentence sounds like it assumes they know what an HMAC is
> Look at how HMAC (Hash Message Authentication Code) is being used. No copy pasting!

but this wasn't explained in the [password management workshop](https://github.com/foundersandcoders/ws-password-management)

There is a link, but this only goes to the node documentation, which explains how you use `crypto.createHmac` but not what an HMAC actually is

**Comment by matthewdking** [comment]
@jsms90 @ronanyeah there is a description of HMAC in the signing section of the README so do we still need to add a description lower down in exercise one as well?

> A [HMAC](https://en.wikipedia.org/wiki/Hash-based_message_authentication_code) (Hash-based message authentication code) is a way to hash a message in order to verify its integrity and authentication. This is important as we need to be sure that:
> 1. We created the hash.
> 2. The message has not changed.
> 
> A HMAC requires a `secret` (random string), a `value` (the string you want to protect) and `mathematical algorithm` to apply to them.
>
> These same three inputs will always produce the _same result_. So you can store the HMAC alongside the original message to verify in future, that the message/cookie/whatever has not been tampered with. This is known as 'signing'.
> 
> Luckily Node.js has a built-in [HMAC function](https://nodejs.org/dist/latest-v8.x/docs/api/crypto.html#crypto_class_hmac).
