### ISSUE TITLE
remove statement about brute force attacks not being relevant

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/ws-session-management#9]
> Note: When protecting a cookie, defence against brute force attacks, such as bcyrpt, is not necessary, for two reasons:

Not sure if this is really true. Brute force attacks still happen against JWTs - https://github.com/jmaxxz/jwtbrute

> 1. Just gaining access to a valid cookie will give you access to all of that users privileges, without any further work.

Only if your cookie's content is not encrypted or signed. If HMAC has been used on it, then you can't just see the user's privileges "without any further work"

> 2. If your application secret is a long random string, used with a powerful enough hash, there is not enough computer power on earth to crack that.

So the vulnerabilities are if the key isn't strong enough https://www.sjoerdlangkemper.nl/2016/09/28/attacking-jwt-authentication/#crack-the-key

There are enough insecure JWT libraries that I don't think this paragraph helps

**Comment by ronanyeah** [comment]
> Only if your cookie's content is not encrypted or signed. If HMAC has been used on it, then you can't just see the user's privileges "without any further work"

I could copy paste it and use it in my browser. Pretty easy.

**Comment by ronanyeah** [comment]
https://crypto.stackexchange.com/a/6753

**Comment by jsms90** [comment]
> I could copy paste it and use it in my browser. Pretty easy.

You could copy and paste what in your browser?

**Comment by ronanyeah** [comment]
The cookie that has been compromised.

Sent from ProtonMail mobile

-------- Original Message --------
